# development environment provisioning
version: "3.5"
services:
  database:
    container_name: accounts_db_mysql
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: accounts
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3307:3306"
    volumes:
      - "../.data/mysql:/var/lib/mysql:Z"
    